import React, {FC} from 'react';
import Head from "next/head";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";


interface MainLayoutProps {
    children: any;
    title: string;
    description?: string;
    keywords?: string;
}

const MainLayout: FC<MainLayoutProps> = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.png"/>

            </Head>

            <div className="container">
                {/*<noscript><div><img src="https://mc.yandex.ru/watch/91951709" style="position:absolute; left:-9999px;" alt="" /></div></noscript>*/}

                <Header/>

                <main className="main">
                    {children}
                </main>

                <Footer/>
            </div>
        </>
    );
};

export default MainLayout;